apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: NodePort
  selector:
    app: todo-app  # Must match the deployment's labels
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
